### ISSUE TITLE
Line endings

### ISSUE THREAD

**Issue by EdFuentetaja** [Microtelecom/libperseus-sdr#2]
First of all, thanks for sharing this and congratulations for the excellent Perseus hardware and software.

I tried to compile this code on Fedora and I noticed that the ASCII files need to be converted first to the UNIX line ending format. You can use a tool like dos2unix,

**Comment by amontefusco** [comment]
> > I tried to compile this code on Fedora and I noticed that the ASCII files need 
> > to be converted first to the UNIX line ending format. You can use a tool like dos2unix,

Which error did you get ?
I never noticed that.

**Comment by amontefusco** [comment]
You are right that the .c and .h files are ending (now always but often) with \r\n sequence instead of \n as usual in *nix.
Probably this is why, in origin, Nico wrote them on Windows or using some Windows editor, and I too lately, did some editing directly on Windows.
However, in my experience, no one of many Unix tools I use ever complained about that (just some cosmetic  ^M on vi is barely visible).
Again, let me know exactly which errors you had, otherwise I cannot help.

**Comment by EdFuentetaja** [comment]
The first error is when executing the bootstrap.sh script:

-bash: ./bootstrap.sh: /bin/sh^M: bad interpreter: No such file or directory

This is coming from the very first line in the file:

#!/bin/sh

The ^M is the additional character for line ending on Windows. For some reason the distribution I'm using (actually CentOS 6.6, not Fedora), doesn't like it.

Applying dos2unix to the script files leads to the next error, more tricky:

libtoolize: AC_CONFIG_MACRO_DIR([build-aux]) conflicts with ACLOCAL_AMFLAGS=-I b.ild-aux
autoreconf: libtoolize failed with exit status: 1

Here it says that it's related to the line ending on the Makefile.am file: http://pete.akeo.ie/2010/12/that-darn-libtoolize-acconfigmacrodirm4.html

Pete also suggest to configure a .gitattributes file. Please see:

https://help.github.com/articles/dealing-with-line-endings/

**Comment by amontefusco** [comment]
>> The first error is when executing the bootstrap.sh script:
>> -bash: ./bootstrap.sh: /bin/sh^M: bad interpreter: No such file or directory

This is more and more strange: if I clone a fresh repository on Ubuntu, the first line of that file is:

andrew@atom330:~/libperseus-sdr$ hexdump -C bootstrap.sh 
00000000  23 21 2f 62 69 6e 2f 73  68 0a 0a 23 20 2d 2d 2d  |#!/bin/sh..# ---|

so two line feeds, no CR at all.
Maybe git is doing automatic translation ?

**Comment by amontefusco** [comment]
Did you try  with:

git config --global core.autocrlf input

?

**Comment by amontefusco** [comment]
And/Or, try to add that .gitattributes  (as per link you copied above) to your clone repository and let me know if it cures the issue.

I don't have at hand  a CentOS 6.6 here, so I cannot test it.

**Comment by EdFuentetaja** [comment]
Aha. I had a global setting of autocrlf = true. This might be the default on CentOS. Changing it to "input" solves the issue, files come up clean of \r.

Thanks! Didn't occur to me to check this setting.
