### ISSUE TITLE
perseustest failed on VirtualBox environment

### ISSUE THREAD

**Issue by Cornie8** [Microtelecom/libperseus-sdr#5]
hi, I want to use my perseus with gnuradio and in a first step i have installed the libperseus-sdr on a virtualbox with ubuntu 14.04.5 64 bit.
If I run the perseustest with the perseus first disconnected and then connected I get the following output:

cornie@cornie-VirtualBox:~/build/libperseus_sdr-0.7.5$ perseustest
Revision: 0.7.5
SAMPLE RATE: 95000
NBUF: 6 BUF SIZE: 1024 TOTAL BUFFER LENGTH: 6144
perseus: perseus_init()
perseus: Executable: perseustest
perseus: path: [] name: []
perseus: Found device with VID/PID 1D6B:0002 on BUS1 ADDR1
perseus: Found device with VID/PID 80EE:0021 on BUS2 ADDR2
perseus: Found device with VID/PID 1D6B:0001 on BUS2 ADDR1
0 Perseus receivers found
No Perseus receivers detected
perseus: perseus_exit(): poll_libusb_thread_flag=0
cornie@cornie-VirtualBox:~/build/libperseus_sdr-0.7.5$ perseustest
Revision: 0.7.5
SAMPLE RATE: 95000
NBUF: 6 BUF SIZE: 1024 TOTAL BUFFER LENGTH: 6144
perseus: perseus_init()
perseus: Executable: perseustest
perseus: path: [] name: []
perseus: Found device with VID/PID 04B4:325C on BUS1 ADDR7
perseus: Found device with VID/PID 1D6B:0002 on BUS1 ADDR1
perseus: Found device with VID/PID 80EE:0021 on BUS2 ADDR2
perseus: Found device with VID/PID 1D6B:0001 on BUS2 ADDR1
1 Perseus receivers found
perseus: perseus_open(0)
perseus: poll libusb thread started...
perseus: setting thread priority to 99...
perseus: done
Downloading firmware...
perseus: perseus_firmware_download(0x7b5440,Null)
perseus: perseus_firmware_download(0x7b5440,Null)
perseus: downloading std firmware to fx2 cpu
perseus: fx2 cpu reset(1) ok...
perseus: fx2 cpu ram write ok...
perseus: fx2 cpu reset(0) ok...
perseus: done
perseus: perseus_close(0x7b5440)
perseus: releasing interface...
perseus: done
perseus: closing device handle...
perseus: re-enumerating usb devices, please wait...
perseus: Found device with VID/PID 04B4:325C on BUS1 ADDR8
perseus: Perseus found on BUS1 ADDR8 after re-enumeration
perseus: Found device with VID/PID 1D6B:0002 on BUS1 ADDR1
perseus: Found device with VID/PID 80EE:0021 on BUS2 ADDR2
perseus: Found device with VID/PID 1D6B:0001 on BUS2 ADDR1
perseus: Please wait...
perseus: try to open the device after re-enumeration...
perseus: perseus_open(0)
perseus: open successful
perseus: reading device eeprom...
perseus error: Fx2 eeprom read command error
perseus error: failed to read device eeprom
firmware download error: failed to read device eepromcornie@cornie-VirtualBox:~/build/libperseus_sdr-0.7.5$

logging out and logging in again makes no difference.
Any ideas?

cornie8

**Comment by amontefusco** [comment]
I observed that ill-behavior in the past: I believe it is something caused by the USB environment in VirtualBox.

Probably it is due to the quite unusual behavior that Perseus hardware exhibits: it is changing VID:PID in the same run.
In fact, after the firmware of Cypress microcontroller inside Perseus is loaded with the right firmware and restarted, the USB PID:VID is changed to a new one and that seems to disrupt the emulation layer in VirtualBox.
